# Generated by Django 4.2.2 on 2023-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "locales_app",
            "0003_localesrepuestos_barrio_localesrepuestos_comida_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="localesrepuestos",
            name="direccion",
            field=models.CharField(max_length=300, verbose_name="direccion"),
        ),
        migrations.AlterField(
            model_name="localesrepuestos",
            name="ventas_proyectadas",
            field=models.CharField(max_length=200, verbose_name="ventas_proyectadas"),
        ),
    ]
